// <auto-generated />
using System;
using DorfInfoBot.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DorfInfoBot.API.Migrations
{
    [DbContext(typeof(NewsContext))]
    [Migration("20210818180938_NewsDBInitialSeeding")]
    partial class NewsDBInitialSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("DorfInfoBot.API.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Attachment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NewsId = 1,
                            PreviewImage = "The most visited urban park in the United States.",
                            Title = "Anhang-News-1.pdf"
                        },
                        new
                        {
                            Id = 2,
                            NewsId = 1,
                            PreviewImage = "A 102-story skyscraper located in Midtown Manhattan.",
                            Title = "Anhang-News-1.pdf"
                        },
                        new
                        {
                            Id = 3,
                            NewsId = 2,
                            PreviewImage = "A Gothic style cathedral, conceived by architects Jan and Pieter Appelmans.",
                            Title = "Anhang-News-2.pdf"
                        },
                        new
                        {
                            Id = 4,
                            NewsId = 2,
                            PreviewImage = "The the finest example of railway architecture in Belgium.",
                            Title = "Anhang-News-2.pdf"
                        },
                        new
                        {
                            Id = 5,
                            NewsId = 3,
                            PreviewImage = "A wrought iron lattice tower on the Champ de Mars, Titled after engineer Gustave Eiffel.",
                            Title = "Anhang-News-3.pdf"
                        },
                        new
                        {
                            Id = 6,
                            NewsId = 3,
                            PreviewImage = "The world's largest museum.",
                            Title = "Anhang-News-3.pdf"
                        });
                });

            modelBuilder.Entity("DorfInfoBot.API.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOriginalPost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullText")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkOriginalPost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOriginalPost = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Details zur Veranstaltung folgen im nächsten \"dierikon informiert.\" und sind auf der Homepage der Gemeinde bereits ab 20. August 2021 aufgeschaltet. Eine Anmeldung wird zwingend notwendig sein.",
                            ExternalKey = "InitKey1",
                            FullText = "",
                            LinkOriginalPost = "https://www.dierikon.ch/aktuellesinformationen/1308194",
                            Title = "Informationsveranstaltung Bahnanlage Dierikon"
                        },
                        new
                        {
                            Id = 2,
                            DateOriginalPost = new DateTime(2021, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Die virtuelle Entdeckungsreise in und um Luzern. Vom 1. bis 31. August 2021 täglich neue Ausflugstipps erhalten und an Gewinnspielen mitmachen.",
                            ExternalKey = "InitKey2",
                            FullText = "",
                            LinkOriginalPost = "https://www.dierikon.ch/aktuellesinformationen/1311797",
                            Title = "Mit der vbl die Stadt Luzern und die Agglomeration entdecken!"
                        },
                        new
                        {
                            Id = 3,
                            DateOriginalPost = new DateTime(2021, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Will einen Pool bauen, so wie alle.",
                            ExternalKey = "InitKey3",
                            FullText = "",
                            LinkOriginalPost = "https://www.dierikon.ch/publikationen/334790",
                            Title = "Baugesuch Hans Mustermann"
                        });
                });

            modelBuilder.Entity("DorfInfoBot.API.Entities.Attachment", b =>
                {
                    b.HasOne("DorfInfoBot.API.Entities.News", "News")
                        .WithMany("Attachment")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("DorfInfoBot.API.Entities.News", b =>
                {
                    b.Navigation("Attachment");
                });
#pragma warning restore 612, 618
        }
    }
}
